INSERT INTO Dishes(ID, FIRST_DISHES, PRICES, DISH_WEIGHT)VALUES('1','BORSCH', 20, 250);
INSERT INTO Dishes(ID, SECOND_DISHES, PRICES, DISH_WEIGHT)VALUES('2','SHAURMA', 40, 350);
INSERT INTO Dishes(ID, THIRD_DISHES, PRICES, DISH_WEIGHT)VALUES('3','PAHLAVA', 400, 100);
 
CREATE TABLE Dishes(
ID CHAR(10) PRIMARY KEY NOT NULL,
FIRST_DISHES CHAR(225)  NULL,
SECOND_DISHES CHAR(225)  NULL,
THIRD_DISHES CHAR(225)  NULL,
SALADS CHAR(225)  NULL,
DRINKS CHAR(225)  NULL,
PRICES INT NOT NULL,
DISH_WEIGHT INT NOT NULL,
);
